version: '3.1'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_DB=dashboard

    ports:
      - "54320:5432"
